/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Instruction</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Instruction#getCmd <em>Cmd</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Instruction#getObj <em>Obj</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Instruction#getParam <em>Param</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getInstruction()
 * @model
 * @generated
 */
public interface Instruction extends Statement
{
  /**
   * Returns the value of the '<em><b>Cmd</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cmd</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cmd</em>' attribute.
   * @see #setCmd(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getInstruction_Cmd()
   * @model
   * @generated
   */
  String getCmd();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Instruction#getCmd <em>Cmd</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cmd</em>' attribute.
   * @see #getCmd()
   * @generated
   */
  void setCmd(String value);

  /**
   * Returns the value of the '<em><b>Obj</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Obj</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Obj</em>' attribute.
   * @see #setObj(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getInstruction_Obj()
   * @model
   * @generated
   */
  String getObj();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Instruction#getObj <em>Obj</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Obj</em>' attribute.
   * @see #getObj()
   * @generated
   */
  void setObj(String value);

  /**
   * Returns the value of the '<em><b>Param</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Param</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Param</em>' attribute.
   * @see #setParam(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getInstruction_Param()
   * @model
   * @generated
   */
  String getParam();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Instruction#getParam <em>Param</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Param</em>' attribute.
   * @see #getParam()
   * @generated
   */
  void setParam(String value);

} // Instruction
