/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Verify</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Verify#getCompare <em>Compare</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Verify#getContains <em>Contains</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getVerify()
 * @model
 * @generated
 */
public interface Verify extends Statement
{
  /**
   * Returns the value of the '<em><b>Compare</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Compare</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Compare</em>' containment reference.
   * @see #setCompare(Compare)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getVerify_Compare()
   * @model containment="true"
   * @generated
   */
  Compare getCompare();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Verify#getCompare <em>Compare</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Compare</em>' containment reference.
   * @see #getCompare()
   * @generated
   */
  void setCompare(Compare value);

  /**
   * Returns the value of the '<em><b>Contains</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Contains</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contains</em>' containment reference.
   * @see #setContains(Contains)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getVerify_Contains()
   * @model containment="true"
   * @generated
   */
  Contains getContains();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Verify#getContains <em>Contains</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Contains</em>' containment reference.
   * @see #getContains()
   * @generated
   */
  void setContains(Contains value);

} // Verify
